### ISSUE TITLE
Error Running Code: FileNotFoundError for AGNews Dataset

### ISSUE THREAD

**Issue by nsaadati** [epfml/personalized-collaborative-llms#4]
Hi,

I encountered an error while trying to run your code. Could you please help me fix it? When I run the reproduce shell, I still get the same error for all the other datasets as well:

python ./src/gen_dataset.py --dataset agnews_mixed
Traceback (most recent call last):
  File "/work/mech-ai-scratch/nsaadati/projects/dlora/personalized-collaborative-llms/./src/gen_dataset.py", line 14, in <module>
    _ = get_dataset(parser.parse_args())
  File "/work/mech-ai-scratch/nsaadati/projects/dlora/personalized-collaborative-llms/src/data/utils.py", line 29, in get_dataset
    return get_agnews_data("mixed")
  File "/work/mech-ai-scratch/nsaadati/projects/dlora/personalized-collaborative-llms/src/data/agnews.py", line 135, in get_agnews_data
    train_data.append(np.memmap(os.path.join(DATA_PATH, f'train_{i}.bin'), dtype=np.uint16, mode='r'))
  File "/home/nsaadati/.local/lib/python3.10/site-packages/numpy/core/memmap.py", line 229, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: '/work/mech-ai-scratch/nsaadati/projects/dlora/personalized-collaborative-llms/src/data/datasets/agnews/mixed/train_0.bin'

Thank you,

**Comment by TheImpressiveDonut** [comment]
Hey,

i hope you could find the problem in the meantime, if not, this issue comes from the way we generate datasets. If the dataset's folder exists, we assume that the dataset is generated and complete. So a quick way to do fix this is to delete the folder of the dataset, in your case "/src/data/datasets/agnews/mixed/", it will generate the dataset again once you run the reproduce script.
